redis:
  image: redis
  ports:
    - '6379:6379'

postgres:
  image: postgres
  environment:
    - POSTGRES_PASSWORD=mysecretpassword
  ports:
    - '5432:5432'

app:
  build: .
  working_dir: /opt/ifsc
  # entrypoint: /entrypoint.sh
  command: mix phx.server
  environment:
    - POSTGRES_DATABASE_USERNAME
    - POSTGRES_DATABASE_PASSWORD=mysecretpassword
    - POSTGRES_DATABASE_NAME
    - POSTGRES_DATABASE_HOST
    - GRAYLOG_HOST
    - GRAYLOG_PORT
    - SENTRY_DSN
    - CUSTOMERIO_SITE_ID
    - CUSTOMERIO_API_KEY
  volumes:
    - '.:/opt/ifsc'
  links:
    - redis
    - postgres
